import { StyleSheet } from "react-native";

export const createCartStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1, 
    padding: 16,
    paddingTop: 0,
    backgroundColor: colors.background,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 15,
    color: colors.textMuted,
    marginTop: 40,
  },
  
  cartItemWrapper: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
    overflow: 'hidden',
  },
  cartItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  expandText: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: '600',
    marginTop: 4,
  },
  accordionContent: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  featureSection: {
    marginTop: 8,
  },
  featureTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  pillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  readOnlyPill: {
    backgroundColor: colors.primary,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  readOnlyPillText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '600',
  },

  itemInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  itemName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  itemPrice: {
    color: colors.success,
    marginTop: 2,
    fontWeight: '600',
    fontSize: 13,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  actionBtn: {
    padding: 8,
    borderRadius: 8,
    width: 32,
    alignItems: 'center',
    backgroundColor: colors.borderLight,
  },
  actionBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  quantity: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  deleteBtn: {
    padding: 8,
  },
  deleteText: {
    color: colors.error,
    fontSize: 16,
  },
  checkoutSection: {
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingTop: 16,
    marginTop: 8,
  },
  totalText: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'right',
    color: colors.textPrimary,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  label: {
    fontSize: 14,
    color: colors.textPrimary,
  },
  addressForm: {
    gap: 8,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    borderRadius: 10,
    fontSize: 14,
    color: colors.textPrimary,
  },
  confirmBtn: {
    backgroundColor: colors.primary,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 3,
  },
  confirmBtnDisabled: {
    backgroundColor: colors.errorBg,
  },
  confirmBtnText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 15,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.surface,
    padding: 28,
    borderRadius: 20,
    width: '85%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  successIcon: {
    fontSize: 56,
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 8,
    color: colors.textPrimary,
  },
  modalMessage: {
    fontSize: 14,
    textAlign: 'center',
    color: colors.textSecondary,
    marginBottom: 20,
    lineHeight: 20,
  },
  modalBtn: {
    backgroundColor: colors.success,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
  },
  modalBtnText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 15,
  }
});
